CREATE TABLE `NOTICE` (
	`NOTICE_PK`	VARCHAR(20)	NOT NULL,
	`CONTENT`	VARCHAR(300)	NULL,
	`WRITER`	VARCHAR(20)	NULL
);

CREATE TABLE `VISITORS` (
	`VISITOR_PK`	VARCHAR(20)	NOT NULL,
	`NOTICE_FK`	VARCHAR(20)	NOT NULL,
	`VISITOR_NAME`	VARCHAR(20)	NULL
);

ALTER TABLE `NOTICE` ADD CONSTRAINT `PK_NOTICE` PRIMARY KEY (
	`NOTICE_PK`
);

ALTER TABLE `VISITORS` ADD CONSTRAINT `PK_VISITORS` PRIMARY KEY (
	`VISITOR_PK`,
	`NOTICE_FK`
);

ALTER TABLE `VISITORS` ADD CONSTRAINT `FK_NOTICE_TO_VISITORS_1` FOREIGN KEY (
	`NOTICE_FK`
)
REFERENCES `NOTICE` (
	`NOTICE_PK`
);

