use db_car;

CREATE TABLE `CAR` (
	`PK_CAR_ID`	VARCHAR(20)	NOT NULL,
	`FK_CN_ID`	VARCHAR(20)	NOT NULL,
	`FK_CP_ID`	VARCHAR(20)	NOT NULL,
	`FK_CY__ID`	VARCHAR(20)	NOT NULL
);

CREATE TABLE `CAR_COMPANY` (
	`PK_CP_ID`	VARCHAR(20)	NOT NULL,
	`COMPANY_NAME`	VARCHAR(20)	NULL
);

CREATE TABLE `CAR_NAME` (
	`PK_CN_ID`	VARCHAR(20)	NOT NULL,
	`CAR_NAME`	VARCHAR(20)	NULL
);

CREATE TABLE `CAR_YEAR` (
	`PK_CY__ID`	VARCHAR(20)	NOT NULL,
	`CAR_YEAR`	VARCHAR(20)	NULL
);

CREATE TABLE `CAR_OPTION` (
	`PK_CO_ID`	VARCHAR(20)	NOT NULL,
	`FK_CAR_ID`	VARCHAR(20)	NOT NULL,
	`OPTION`	VARCHAR(30)	NULL
);

ALTER TABLE `CAR` ADD CONSTRAINT `PK_CAR` PRIMARY KEY (
	`PK_CAR_ID`,
	`FK_CN_ID`,
	`FK_CP_ID`,
	`FK_CY__ID`
);

ALTER TABLE `CAR_COMPANY` ADD CONSTRAINT `PK_CAR_COMPANY` PRIMARY KEY (
	`PK_CP_ID`
);

ALTER TABLE `CAR_NAME` ADD CONSTRAINT `PK_CAR_NAME` PRIMARY KEY (
	`PK_CN_ID`
);

ALTER TABLE `CAR_YEAR` ADD CONSTRAINT `PK_CAR_YEAR` PRIMARY KEY (
	`PK_CY__ID`
);

ALTER TABLE `CAR_OPTION` ADD CONSTRAINT `PK_CAR_OPTION` PRIMARY KEY (
	`PK_CO_ID`,
	`FK_CAR_ID`
);

ALTER TABLE `CAR` ADD CONSTRAINT `FK_CAR_NAME_TO_CAR_1` FOREIGN KEY (
	`FK_CN_ID`
)
REFERENCES `CAR_NAME` (
	`PK_CN_ID`
);

ALTER TABLE `CAR` ADD CONSTRAINT `FK_CAR_COMPANY_TO_CAR_1` FOREIGN KEY (
	`FK_CP_ID`
)
REFERENCES `CAR_COMPANY` (
	`PK_CP_ID`
);

ALTER TABLE `CAR` ADD CONSTRAINT `FK_CAR_YEAR_TO_CAR_1` FOREIGN KEY (
	`FK_CY__ID`
)
REFERENCES `CAR_YEAR` (
	`PK_CY__ID`
);

ALTER TABLE `CAR_OPTION` ADD CONSTRAINT `FK_CAR_TO_CAR_OPTION_1` FOREIGN KEY (
	`FK_CAR_ID`
)
REFERENCES `CAR` (
	`PK_CAR_ID`
);

