USE db_car_company;
CREATE TABLE `INFO` (
	`Key`	VARCHAR(20)	NOT NULL,
	`FK_CN_ID`	VARCHAR(20)	NOT NULL,
	`FK_CY_ID`	VARCHAR(20)	NOT NULL,
	`FK_CP_ID`	VARCHAR(20)	NOT NULL
);

CREATE TABLE `NAME` (
	`PK_CN_ID`	VARCHAR(20)	NOT NULL,
	`CAR_NAME`	VARCHAR(20)	NULL
);

CREATE TABLE `YEAR` (
	`PK_CY_ID`	VARCHAR(20)	NOT NULL,
	`CAR_YEAR`	VARCHAR(20)	NULL
);

CREATE TABLE `COMPANY` (
	`PK_CP_ID`	VARCHAR(20)	NOT NULL,
	`CAR_COMPANY`	VARCHAR(20)	NULL
);

CREATE TABLE `OPTION` (
	`PK_OPT_ID`	VARCHAR(20)	NOT NULL,
	`CAR_OPTION`	VARCHAR(30)	NULL
);

CREATE TABLE `CAR_OPTION` (
	`PK_CO_ID`	VARCHAR(20)	NOT NULL,
	`FK_OPT_ID`	VARCHAR(20)	NOT NULL,
	`FK_CAR_INFO_ID`	VARCHAR(20)	NOT NULL
);

ALTER TABLE `INFO` ADD CONSTRAINT `PK_INFO` PRIMARY KEY (
	`Key`,
	`FK_CN_ID`,
	`FK_CY_ID`,
	`FK_CP_ID`
);

ALTER TABLE `NAME` ADD CONSTRAINT `PK_NAME` PRIMARY KEY (
	`PK_CN_ID`
);

ALTER TABLE `YEAR` ADD CONSTRAINT `PK_YEAR` PRIMARY KEY (
	`PK_CY_ID`
);

ALTER TABLE `COMPANY` ADD CONSTRAINT `PK_COMPANY` PRIMARY KEY (
	`PK_CP_ID`
);

ALTER TABLE `OPTION` ADD CONSTRAINT `PK_OPTION` PRIMARY KEY (
	`PK_OPT_ID`
);

ALTER TABLE `CAR_OPTION` ADD CONSTRAINT `PK_CAR_OPTION` PRIMARY KEY (
	`PK_CO_ID`,
	`FK_OPT_ID`,
	`FK_CAR_INFO_ID`
);

ALTER TABLE `INFO` ADD CONSTRAINT `FK_NAME_TO_INFO_1` FOREIGN KEY (
	`FK_CN_ID`
)
REFERENCES `NAME` (
	`PK_CN_ID`
);

ALTER TABLE `INFO` ADD CONSTRAINT `FK_YEAR_TO_INFO_1` FOREIGN KEY (
	`FK_CY_ID`
)
REFERENCES `YEAR` (
	`PK_CY_ID`
);

ALTER TABLE `INFO` ADD CONSTRAINT `FK_COMPANY_TO_INFO_1` FOREIGN KEY (
	`FK_CP_ID`
)
REFERENCES `COMPANY` (
	`PK_CP_ID`
);

ALTER TABLE `CAR_OPTION` ADD CONSTRAINT `FK_OPTION_TO_CAR_OPTION_1` FOREIGN KEY (
	`FK_OPT_ID`
)
REFERENCES `OPTION` (
	`PK_OPT_ID`
);

ALTER TABLE `CAR_OPTION` ADD CONSTRAINT `FK_INFO_TO_CAR_OPTION_1` FOREIGN KEY (
	`FK_CAR_INFO_ID`
)
REFERENCES `INFO` (
	`Key`
);

