CREATE TABLE `INFOS` (
	`USER_PK_ID`	VARCHAR(20)	NOT NULL,
	`USERNAME`	VARCHAR(20)	NULL,
	`AGE`	INT	NULL,
	`PHONE_NUMBER`	VARCHAR(30)	NULL,
	`EMAIL`	VARCHAR(30)	NULL,
	`GENDER`	VARCHAR(10)	NULL
);

CREATE TABLE `HOBBYS` (
	`HOBBY_PK_ID`	VARCHAR(20)	NOT NULL,
	`HOBBY`	VARCHAR(20)	NULL
);

CREATE TABLE `USER_HOBBY` (
	`USER_HOB_PK_ID`	VARCHAR(20)	NOT NULL,
	`USER_PK_ID`	VARCHAR(20)	NOT NULL,
	`HOBBY_FK_ID`	VARCHAR(20)	NOT NULL
);

CREATE TABLE `ADDRESS` (
	`ADDRESS_PK_ID`	VARCHAR(20)	NOT NULL,
	`ADDRESS`	VARCHAR(30)	NULL
);

CREATE TABLE `USER_ADDRESS` (
	`USER_ADDR_PK_ID`	VARCHAR(20)	NOT NULL,
	`USER_FK_ID`	VARCHAR(20)	NOT NULL,
	`ADDRESS_FK_ID`	VARCHAR(20)	NOT NULL
);

ALTER TABLE `INFOS` ADD CONSTRAINT `PK_INFOS` PRIMARY KEY (
	`USER_PK_ID`
);

ALTER TABLE `HOBBYS` ADD CONSTRAINT `PK_HOBBYS` PRIMARY KEY (
	`HOBBY_PK_ID`
);

ALTER TABLE `USER_HOBBY` ADD CONSTRAINT `PK_USER_HOBBY` PRIMARY KEY (
	`USER_HOB_PK_ID`,
	`USER_PK_ID`,
	`HOBBY_FK_ID`
);

ALTER TABLE `ADDRESS` ADD CONSTRAINT `PK_ADDRESS` PRIMARY KEY (
	`ADDRESS_PK_ID`
);

ALTER TABLE `USER_ADDRESS` ADD CONSTRAINT `PK_USER_ADDRESS` PRIMARY KEY (
	`USER_ADDR_PK_ID`,
	`USER_FK_ID`,
	`ADDRESS_FK_ID`
);

ALTER TABLE `USER_HOBBY` ADD CONSTRAINT `FK_INFOS_TO_USER_HOBBY_1` FOREIGN KEY (
	`USER_PK_ID`
)
REFERENCES `INFOS` (
	`USER_PK_ID`
);

ALTER TABLE `USER_HOBBY` ADD CONSTRAINT `FK_HOBBYS_TO_USER_HOBBY_1` FOREIGN KEY (
	`HOBBY_FK_ID`
)
REFERENCES `HOBBYS` (
	`HOBBY_PK_ID`
);

ALTER TABLE `USER_ADDRESS` ADD CONSTRAINT `FK_INFOS_TO_USER_ADDRESS_1` FOREIGN KEY (
	`USER_FK_ID`
)
REFERENCES `INFOS` (
	`USER_PK_ID`
);

ALTER TABLE `USER_ADDRESS` ADD CONSTRAINT `FK_ADDRESS_TO_USER_ADDRESS_1` FOREIGN KEY (
	`ADDRESS_FK_ID`
)
REFERENCES `ADDRESS` (
	`ADDRESS_PK_ID`
);

