SELECT * FROM ADDRESS;
SELECT * FROM HOBBYS;
SELECT * FROM INFOS;
SELECT * FROM USER_ADDRESS;
SELECT * FROM USER_HOBBY;

SELECT i.USERNAME AS '이름', count(h.HOBBY_PK_ID) AS '취미갯수', i.AGE AS '나이', i.GENDER AS '성별', MIN(a.ADDRESS) AS '배송 주소' FROM INFOS i
JOIN 
(SELECT USER_FK_ID, MIN(ADDRESS_FK_ID) AS ADDRESS_FK_ID FROM USER_ADDRESS
GROUP BY USER_FK_ID) ua ON i.USER_PK_ID = ua.USER_FK_ID
JOIN ADDRESS a ON ua.ADDRESS_FK_ID = a.ADDRESS_PK_ID
JOIN USER_HOBBY uh ON i.USER_PK_ID = uh.USER_PK_ID
JOIN HOBBYS h ON uh.HOBBY_FK_ID = h.HOBBY_PK_ID
GROUP BY i.USERNAME, i.AGE, i.GENDER, a.ADDRESS
;